### ISSUE TITLE
Color of holding peice changing

### ISSUE THREAD

**Issue by ALittlePatate** [busybox11/projet-final-nsi#1]
When you press your hold key, the piece in the hold slot will have it's color changed ;)

**Comment by busybox11** [comment]
Actually that's a feature.
When you're holding a piece, it is turning gray to indicate you can't hold for this turn anymore.
Then, after this piece, the next one is going to re-add the hold piece's color to indicate that the hold is available.

**Comment by ALittlePatate** [comment]
ok this is big brain actually

**Comment by busybox11** [comment]
I know right?!
cc @Jossl123
